FROM php:8.2-cli

# Install necessary extensions and tools
RUN apt-get clean && apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libicu-dev \
    libc-client-dev \
    libkrb5-dev \
    unzip \
    curl \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install -j$(nproc) intl imap zip mysqli gd exif bcmath iconv \
    && pecl install apcu \
    && docker-php-ext-enable apcu imap mysqli

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . /app

# Change to the directory where composer.json is located
WORKDIR /app/src

# Install dependencies with superuser permissions
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist --optimize-autoloader

# Set the working directory back to /app
WORKDIR /app

# Use project-specific PHPUnit
CMD ["./src/vendor/bin/phpunit", "--configuration", "/app/tests/phpunit.xml"]